{% set name = "perscache" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/perscache-{{ version }}.tar.gz
  sha256: e56b7611b26d41c3dc457ccd00bf65f0a429c892e62d7dd74f1bddb67e419aca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pbr
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - beartype
    - cloudpickle
    - icontract

test:
  imports:
    - perscache
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/leshchenko1979/perscache
  summary: 'An easy to use decorator for persistent memoization: like `functools.lrucache`, but results can be saved in any format to any storage.'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
